spring.application.name=martial-arts-backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/martial_arts_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=${UPLOAD_DIR:${user.home}/karate_uploads}

spring.web.resources.static-locations=classpath:/static/,classpath:/templates/,${UPLOAD_LOCATION:file:///${user.home}/karate_uploads/}